### ISSUE TITLE
ELIN is broken since Evernote 6.43 & Java 8 update 1.41

### ISSUE THREAD

**Issue by txquestor** [CoreParadox/EvernoteLinkInNote#2]
Hi,

Great Program!  I use it everyday.

As you can see by the title, It quit working.
I know you don't support it anymore.
However could you tell me what Software & version number you used to create ELIN?
I would like to recompile it with the latest versions of software to see if I can fix it.

Thanks for a highly productive program.
Richard

**Comment by SugoiDev** [comment]
@txquestor I have my own program (using Autohotkey) for anchors and noticed it stopped working too.
I use pretty much the same technique as ELIN.

If you edit the raw html (eml actually), you can make the anchor work. But, Evernote will kill your anchor the moment you copy/paste the text that contains the anchor.

I tried to find a way to make it work, but I'm still in the dark. I'll let you know if I ever find a fix for this.

You can use this little greasy monkey script to edit the raw html of your notes using the web interface: https://greasyfork.org/en/scripts/8869-evernote-web-html-editor

---

Now, about your question. ELIN is just a single java file. Just copy the .java and the .fxml files to the same dir and run it with `java EvernoteLinkInNote.java`

The issue isn't in the program, but in the way Evernote strips the link information when it is an "invalid" link.

**Comment by txquestor** [comment]
@SugoiDev 

Thanks for the quick response!

I'll try your solutions to see if it makes a difference & let you know.

R

**Comment by txquestor** [comment]
@SugoiDev 

I tried this "java EvernoteLinkInNote.java"
Worked it created the app fine.

I'd really appreciate if you could explain more details re: this comment
I'd like to understand how this works.
"The issue isn't in the program, but in the way Evernote strips the link information when it is an "invalid" link."

Thanks,
R

**Comment by txquestor** [comment]
@SugoiDev

I tried this "java EvernoteLinkInNote.java"
 Worked it created the app fine.

I'd really appreciate if you could explain more details re: this comment
 I'd like to understand how this works.
 "The issue isn't in the program, but in the way Evernote strips the link information when it is an "invalid" link."

Thanks,
 R

**Comment by SugoiDev** [comment]
@txquestor 

This program, ELIN, is working as it should. But, the anchors are not working (at least on Evernote for Windows) because Evernote is stripping the actual link from the note.

ELIN works by creating an especially formatted text and using the clipboard API to put this text in the HTML part of the clipboard.
The created text would look something like this (I removed the styling part for brevity):

```
Version:1.0
StartHTML:0000000128
EndHTML:0000001588
StartFragment:0000000160
EndFragment:0000001556
SourceURL:about:blank
<HTML><BODY><!--StartFragment--><a href="file:///#jump name">destination</a><!--EndFragment--></BODY></HTML> 
```

You can use a program like [freeClipViewer](http://www.freeclipboardviewer.com/) to see the contents of the text when you copy from ELIN.
It would look like this:

![screenshot 2017 11 18-14 11 51](https://user-images.githubusercontent.com/7355630/32982630-8517745c-cc6e-11e7-9cb3-678006956c69.png)

![screenshot 2017 11 18-14 11 53](https://user-images.githubusercontent.com/7355630/32982631-88e7a1f6-cc6e-11e7-8454-3d39cbbca2df.png)


---

Since Evernote supports rich text/HTML, it should accept your clipboard contents and the anchors should work. 
But, for the past few versions, another step was added and this step removes links Evernote deems "invalid".
You can see the anchors will still work if you create them using something to edito the raw HTML of the note (like the greasymonkey script I mentioned in the first reply), but the links will be broken the moment you move them around in the note (copy/paste, for example).
